server:
  port: 8081

dtm:
  ipport: '127.0.0.1:36789'

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dtm_busi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
